import { ApiProperty } from '@nestjs/swagger';
import {
  IsNotEmpty,
  IsOptional,
  IsString,
  MaxLength,
  IsNumber,
} from 'class-validator';

export class CreateUserDto {
  @ApiProperty({
    example: 'nano_id_handover_token',
    description: 'The secure handover token received from /auth/callback',
  })
  @IsString()
  @IsNotEmpty()
  socialToken: string;

  @ApiProperty({
    example: 'custom_user_id',
    description: 'The public ID for the user (can be generated by FE or BE)',
  })
  @IsString()
  @IsNotEmpty()
  userId: string;

  @ApiProperty({ example: 'CoffeeLover' })
  @IsString()
  @MaxLength(30)
  nickname: string;

  @ApiProperty({ example: 'starbucks', description: 'Brand name from FE' })
  @IsString()
  brand: string;

  @ApiProperty({ example: 'I love espresso!', required: false })
  @IsOptional()
  @IsString()
  @MaxLength(50)
  aboutMe?: string;

  @ApiProperty({ example: 'https://r2.dev/photo.png', required: false })
  @IsOptional()
  @IsString()
  profileUrl?: string;

  @ApiProperty({ example: 1, description: '0: Mutual, 1: Public' })
  @IsNumber()
  @IsOptional()
  visibility?: number;
}
